version: "3.8"
services:
  drupal:
    image: drupal:11
    container_name: drupal_git
    restart: always
    ports:
      - "8084:80"

    volumes:
      - ./modules:/var/www/html/modules
      - ./profiles:/var/www/html/profiles
      - ./themes:/var/www/html/themes
      - ./sites:/var/www/html/sites
    environment:
      DRUPAL_DB_HOST: db:3306
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: drupal_db_git
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_drupal_git
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8085:80"
    depends_on:
      - db
volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  mysql_data:
